// client/src/component/Register.jsx
import React from "react"
import Cookies from "universal-cookie"
import Cjs from "crypto-js"

const cookies = new Cookies()

const Register = () => {
  const user = cookies.get("user")

  const [fname, setFname] = React.useState("")
  const [name, setName] = React.useState("")
  const [pw, setPw] = React.useState("")
  const [repw, setRepw] = React.useState("")

  const fnameChange = (e) => setFname(e.target.value)
  const nameChange = (e) => setName(e.target.value)
  const pwChange = (e) => setPw(e.target.value)
  const repwChange = (e) => setRepw(e.target.value)
  
  const [msg, setMsg] = React.useState()

  const signUp = (exist) => {
    if(!name || !pw || !repw || !fname ) setMsg("Input must be filled")
    else if(pw.length < 8) setMsg("Password must be 8 digit")
    else if(pw !== repw) setMsg("Password & Repassword must be same")
    else if(!exist){
      const encpw = Cjs.AES.encrypt(pw, process.env.PSPH.toString()).toString()
      fetch("/api?for=register&&fname="+fname+"&&name="+name+"&&pw="+encpw)
      window.location.href = "/"
    }
    else setMsg("Username already used")
  }

  const getSign = () => {
    fetch("/api?for=login&&user="+name)
    .then(res => res.json())
    .then(data => { data.uname ? signUp(true) : signUp(false) })
  }

  if(user != null) window.location.href = "/"
  else return (
    <div className="login-page">
      <h1>Syscuhl App</h1>
       {msg}<br />
       <label>Name</label><br />
       <input type="text" value={fname} onChange={fnameChange}/><br />
       <label>Username</label><br />
       <input type="text" value={name} onChange={nameChange}/><br />
       <label>Password</label><br />
       <input type="password" value={pw} onChange={pwChange}/><br />
       <label>Re-Password</label><br />
       <input type="password" value={repw} onChange={repwChange} /><br />
       <button onClick={getSign}>Register</button><br />
    </div>
  )
}

export default Register

// src/component/Register.svelte
<script>
	import { cktool } from "./cktool.js"

	let user = cktool.get("user")

	let id = ""
	let name = ""
	let password = ""
	let repassword = ""
	let tiers = []
	let tier
	let msg = ""

	function getTiers(){
		fetch("/api?for=list-tiers")
		.then(res => res.json())
		.then(data => {
			tiers = data
			tier = data[0].id
		})
	}
	if(!user) getTiers()

	function submit(){
		if(!id || !name || !password || !repassword) msg = "Input must be filled"
		else if(id.length < 6) msg = "Username must be more 6 character"
		else if(password.length < 8) msg = "Password must be more 8 character"
		else if(password != repassword) msg = "Password and repassword must be same"
		else {
			auth()
		}
	}

	function auth(){
		fetch("/api?for=exist&&id="+id)
		.then(res => res.json())
		.then(data => {
			if(data.id) msg = "Username already used"
			else add()
		})
		.catch(err => { throw err })
	}
	function add(){
		fetch("/api?for=register&&id="+id+"&&pw="+password+"&&name="+name+"&&tier="+tier)
		.then(res => res.json())
		.then(data => {
			if(data.succes){
				location.href = "/"
			}
		})
		.catch(err => { throw err })
	}
</script>
{ #if !user }
<h1>Register</h1>
<strong>{msg}</strong><br />
<strong>Username</strong><br />
<input type="text" bind:value={id}><br />
<strong>Name</strong><br />
<input type="text" bind:value={name}><br />
<strong>Password</strong><br />
<input type="password" bind:value={password}><br />
<strong>Re-Password</strong><br />
<input type="password" bind:value={repassword}><br />
<strong>Tiers</strong>
<select bind:value={tier}>
{ #each tiers as tir }
<option value={tir.id}>{tir.name}</option>
{ /each }
</select>
<button on:click={submit}>Submit</button>
{ :else }
<script>
	location.href = "/"
</script>
{ /if }
