// client/src/App.jsx
import React from "react"

import Index from "./component/Index"
import Login from "./component/Login"
import Register from "./component/Register"
import "./style.css"

function Router(props) {
  if(window.location.pathname === props.path)
    return <props.page />
}

class App extends React.Component{
  render() {
    return (
      <div class="App">
        <Router path="/" page={Index} />
        <Router path="/login" page={Login} />
        <Router path="/register" page={Register} />
      </div>
    )
  }
}

export default App

// src/App.svelte
<script>
	import Index from "./component/Index.svelte"
	import Login from "./component/Login.svelte"
	import Register from "./component/Register.svelte"

	let path = location.pathname
</script>
{ #if path === "/" }
<Index />
{ :else if path === "/login" }
<Login />
{ :else if path === "/register" }
<Register />
{ :else }
Error 404 Not Found
{ /if }
